version: '3.1'
services:
  web:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons/pms_be_data:/mnt/pms_be_data
      - ./addons/theme_snippet:/mnt/theme_snippet
      - ./addons/theme_calendar:/mnt/theme_calendar
      - ./addons/agilorg_snippet:/mnt/agilorg_snippet
      - ./addons/my_library:/mnt/my_library

    command: odoo --dev=xml
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: